{% set name = "inifile" %}
{% set version = "0.4.1" %}
{% set hash = "d9e5eb4708ebf13353c4cfce798ad47890a8bcc5fbae04630223d15d79f55e96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - inifile

about:
  home: https://github.com/mitsuhiko/python-inifile
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A small INI library for Python.

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
    - cav71
