travis:
  secure:
    BINSTAR_TOKEN: w/3aLrIpfafDiBoesPJheJWGzyDNkl60CQgQU6flnYq6XlEwbeLSQLzBtPglg2rpJY4w5yHdK8aL8pR7pc9t1L7GdY6FnlU6nlGkWAsecY/IW5f9W3RwjSK+rsOyFniJ1nTCgjbCDLVxVdxjLQeqCIaCnyD74jp2gwa6a+pqr6DHJGoIXwcgNkSdQ1ZcQcPJ60IlAIvYUqBOaNMGXAEla7xOou8W/U1bewEOyp1hOgXMW8Vfub444RE1O49TqQ4NOvrma635GsTJgxRhmziJuTSL93ytNFhtVAzgg/If+CTuo6Iqt+JcdO5UsaH3xY98aqOIwCC/Q1+MyFIaufB9v+hg1xnMQmQjiQNAzc76QHh5sLcYwYiFun5mzbSlQUwoM7TAzsoycH6FsOFZsykdC7bK2WDMGoN1PDpmO8npy4gYsR3Ch08IOmXO7AnTS3UZ7JKfWJChqc6Rvcl2tJounZ7OL2+5dPMfws4XeN4oP1R9hks+95L7i7+70rP7AyKWL0X7zZcStQLnwko97BwEpF7nfyokMJm8ezLPj2xG5VNBAUnsAGxPHgUBEqrhjiIF+uB8JbbMFmnCfCYhCCWaccA0vbXmEnS+s1WlSn5Kl0Bdu+xsyu+cEm5Cf9PIuo1wWZHzZcerPlMTpIuOiOEGgAEZZaspjQPFQbuZDGK6joo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
