travis:
  secure:
    BINSTAR_TOKEN: kSkNkrIM8UiwCJeyAdSEqVGBHNMRNMVo+k+qvxhIiDqrXyEN4VzYrbEcVAuS1tGB91eoWvfFOoYGXHAbkQxdjz8QOLhORJ4sLHP6+jFZ6tVabFV5CvSoSTSbHADPAr1hhdDNU8ZOuKkw8sBnisJdlu/5A8Z6uv1xIcW7kbjeOwUsTh01Lktu2xA7cXxpY3MYhN2ZLLJF3yPS7mL2mdHFiTPicwK5hEQBp8U6x8tQIMev7mcqtAuhT5ttTnORx7ezWtP3tO5Sx4kaJZpyqhmEeI7p8lRDQUngYwKhmw+4Ao5rfBxsYdjZgSj7BovKC4viDozaSFm/fMCY+wA4bnZ/7yTsAzsX+r1LYST+B7yZOd7gFCaQIIJ1rNvf92rzUeCP9by9zgN/fCU0GwOVOKqx09xl++5BTr1A8DpHlbc9saFhgIul3MZRiPNUQLQmNu8wdNIEUDsC5Azbj7e9lS/fSSjWlh3zflXKAC6i9bvVlm+ib1uDG8jdjtbJ6cLqcJVyg3iSV53sHh56oDh+Jlyjrc8WoWia1InCz92vaD51CyFifumwKZbmxA7dHh4KZRS6smATXEcgHOHe4hGOUQ2pF5AEThOhyoDHjvWWdSh3xc9Q32WCeRsB+/4EjItPJD7afJiZsWK+WZY5QChBlmvyUwpUKZOX4MsuBjD5MQUoM0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
